# Generated by Django 6.0.3 on 2026-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Sandwich', 'Sandwich'), ('Fried_Rice', 'Fried_Rice'), ('Biryani', 'Biryani'), ('Manchurian', 'Manchurian'), ('Noodles', 'Noodles'), ('Pasta', 'Pasta')], max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='food/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('image', models.ImageField(upload_to='orders/')),
            ],
        ),
    ]
