# Generated by Django 6.0.3 on 2026-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_restaurant_comment_created_at_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
